// dave-menu.js — Split-dropdown navigation for the Dave personal group
// xarta-node Blueprints GUI
//
// Thin wrapper around createHubMenu() (hub-menu.js).

'use strict';

const DaveActionIcons = {
    refresh: 'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 24 24%22%3E%3Cpath fill=%22black%22 d=%22M13 3a9 9 0 1 0 8.95 10h-2.02A7 7 0 1 1 12 5a6.97 6.97 0 0 1 4.24 1.43L13 10h8V2l-3.33 3.33A8.97 8.97 0 0 0 13 3z%22/%3E%3C/svg%3E',
    newEntry: 'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 24 24%22%3E%3Cpath fill=%22black%22 d=%22M11 5h2v6h6v2h-6v6h-2v-6H5v-2h6V5z%22/%3E%3C/svg%3E',
    folder: 'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 24 24%22%3E%3Cpath fill=%22black%22 d=%22M4 5h6l2 2h8v12H4V5zm2 4v8h12V9H6z%22/%3E%3C/svg%3E',
    document: 'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 24 24%22%3E%3Cpath fill=%22black%22 d=%22M6 2h8l5 5v15H6V2zm7 1.5V8h4.5L13 3.5zM8 12h8v2H8v-2zm0 4h8v2H8v-2z%22/%3E%3C/svg%3E',
    filter: 'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 24 24%22%3E%3Cpath fill=%22black%22 d=%22M3 5h18v2H3V5zm4 6h10v2H7v-2zm3 6h4v2h-4v-2z%22/%3E%3C/svg%3E',
    shield: 'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 24 24%22%3E%3Cpath fill=%22black%22 d=%22M12 2 4 5v6c0 5 3.4 9.7 8 11 4.6-1.3 8-6 8-11V5l-8-3zm-1 14-4-4 1.4-1.4 2.6 2.6 5.6-5.6L18 9l-7 7z%22/%3E%3C/svg%3E',
    run: 'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 24 24%22%3E%3Cpath fill=%22black%22 d=%22M8 5v14l11-7L8 5z%22/%3E%3C/svg%3E',
    link: 'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 24 24%22%3E%3Cpath fill=%22black%22 d=%22M3.9 12a5 5 0 0 1 5-5H12v2H8.9a3 3 0 0 0 0 6H12v2H8.9a5 5 0 0 1-5-5zm5.1 1v-2h6v2H9zm3-6h3.1a5 5 0 0 1 0 10H12v-2h3.1a3 3 0 0 0 0-6H12V7z%22/%3E%3C/svg%3E',
    explain: 'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 24 24%22%3E%3Cpath fill=%22black%22 d=%22M11 18h2v-2h-2v2zm1-16a10 10 0 1 0 0 20 10 10 0 0 0 0-20zm0 18a8 8 0 1 1 0-16 8 8 0 0 1 0 16zm0-14a3 3 0 0 0-3 3h2a1 1 0 1 1 1 1c-1.1 0-2 .9-2 2v2h2v-2a3 3 0 0 0 0-6z%22/%3E%3C/svg%3E',
    calendar: 'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 24 24%22%3E%3Cpath fill=%22black%22 d=%22M7 2h2v2h6V2h2v2h3v18H4V4h3V2zm11 8H6v10h12V10zM6 8h12V6H6v2zm2 4h3v3H8v-3zm5 0h3v3h-3v-3z%22/%3E%3C/svg%3E',
    edit: 'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 24 24%22%3E%3Cpath fill=%22black%22 d=%22M4 17.2V20h2.8L17.1 9.7l-2.8-2.8L4 17.2zM19.3 7.5c.4-.4.4-1 0-1.4l-1.4-1.4a1 1 0 0 0-1.4 0l-1.1 1.1 2.8 2.8 1.1-1.1z%22/%3E%3C/svg%3E',
    complete: 'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 24 24%22%3E%3Cpath fill=%22black%22 d=%22m9 16.2-3.5-3.5L4 14.2 9 19 20.5 7.5 19 6z%22/%3E%3C/svg%3E',
    archive: 'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 24 24%22%3E%3Cpath fill=%22black%22 d=%22M4 4h16v5H4V4zm2 7h12v9H6v-9zm3 2v2h6v-2H9zM6 6v1h12V6H6z%22/%3E%3C/svg%3E',
};

const DaveMenuConfig = createHubMenu({
    storageKey:      'blueprintsDaveMenuConfig',
    group:           'dave',
    toggleId:        'daveMenuToggle',
    tabsId:          'daveHubTabs',
    currentLabelId:  'daveCurrentTabLabel',
    saveButtonId:    'daveMenuSaveButton',
    resetButtonId:   'daveMenuResetButton',
    editorListId:    'daveMenuEditorList',
    notificationId:  'daveMenuSaveNotification',
    resetConfirmMsg: 'Reset Dave navbar to default layout?',
    mobilePinnedId:  'dave-layout',
    pinnedTabsId:    'daveHubTabsPinned',
    syncDefaultItemText: true,
    contextMenuColumns(activeId, items) {
        const byId = new Map((items || []).map(item => [item.id, item]));
        const groupedIds = activeId === 'email'
            ? [
                [
                    'email-refresh',
                    'email-browse-folders',
                    'email-view-plain',
                    'email-view-html',
                    'email-view-markdown',
                    'email-toggle-list',
                ],
                [
                    'email-safe-checks',
                ],
            ]
            : activeId === 'calender'
            ? [
                [
                    'calendar-view-cycle',
                    'calendar-refresh',
                    'calendar-view-year',
                    'calendar-view-month',
                    'calendar-mode-day',
                    'calendar-mode-week',
                    'calendar-selected',
                    'calendar-day-items',
                    'calendar-upcoming',
                ],
                [
                    'calendar-filters',
                    'calendar-filter-settings',
                    'calendar-filter-all',
                    'calendar-filter-tasks',
                    'calendar-filter-kanban',
                    'calendar-filter-git',
                    'calendar-search',
                    'calendar-provenance',
                ],
                [
                    'calendar-new-event',
                    'calendar-create-task',
                    'calendar-edit-event',
                    'calendar-connect-kanban',
                    'calendar-link-diary',
                    'calendar-open-source',
                    'calendar-explain',
                    'calendar-safe-checks',
                ],
            ]
            : activeId === 'diary'
            ? [
                [
                    'diary-view-cycle',
                    'diary-refresh',
                    'diary-view-year',
                    'diary-view-month',
                    'diary-mode-week',
                    'diary-mode-day',
                    'diary-selected',
                    'diary-day-items',
                    'diary-upcoming',
                ],
                [
                    'diary-filters',
                    'diary-filter-settings',
                    'diary-filter-all',
                    'diary-filter-manual',
                    'diary-filter-sources',
                    'diary-filter-git',
                    'diary-search',
                    'diary-provenance',
                ],
                [
                    'diary-new-entry',
                    'diary-run-summary',
                    'diary-browse-folder',
                    'diary-browse-ledger',
                    'diary-connect-kanban',
                    'diary-show-pin-private',
                    'diary-explain-event',
                    'diary-safe-checks',
                ],
            ]
            : null;
        if (!groupedIds) return null;
        const columns = groupedIds.map(ids => ids.map(id => byId.get(id)).filter(Boolean));
        const used = new Set(columns.flat().map(item => item.id));
        const leftovers = (items || []).filter(item => !used.has(item.id));
        if (leftovers.length) columns[columns.length - 1].push(...leftovers);
        return columns;
    },
    defaultMenu: [
        { id: 'diary',       label: 'Diary',    icon: 'icons/ui/diary-blue.svg',    pageLabel: 'Diary',         parent: null,    order: 0 },
        { id: 'calender',    label: 'Calendar', icon: 'icons/ui/calender-blue.svg', pageLabel: 'Calendar',      parent: 'diary', order: 0 },
        { id: 'todo',        label: 'ToDo',     icon: 'icons/ui/todo-blue.svg',     pageLabel: 'ToDo',          parent: 'diary', order: 1 },
        { id: 'email',       label: 'Email',    icon: 'icons/ui/rich-document-blue.svg', pageLabel: 'Email',    parent: 'diary', order: 2 },
        { id: 'imports',     label: 'Imports',  icon: 'icons/ui/imports-blue.svg',  pageLabel: 'Imports',       parent: null,    order: 1 },
        { id: 'dave-layout', label: '☰',        icon: 'icons/hieroglyphs/kheper-gold.svg', pageLabel: 'Navbar Layout', parent: null, order: 2 },
        { id: 'diary-view-cycle', label: 'View', icon: DaveActionIcons.calendar, pageLabel: 'Cycle Diary View', parent: 'dave-layout', order: 0, fn: 'diary.toggleContentView', activeOn: ['diary'] },
        { id: 'diary-filters', label: 'Filters', icon: DaveActionIcons.filter, pageLabel: 'Diary Filters', parent: 'dave-layout', order: 1, fn: 'diary.showFilters', activeOn: ['diary'] },
        { id: 'diary-filter-settings', label: 'Filter Settings', icon: DaveActionIcons.filter, pageLabel: 'Diary Filter Settings', parent: 'dave-layout', order: 2, fn: 'diary.showFilterSettings', activeOn: ['diary'] },
        { id: 'diary-selected', label: 'Selected', icon: DaveActionIcons.document, pageLabel: 'Selected Range Visible Items', parent: 'dave-layout', order: 3, fn: 'diary.showSelected', activeOn: ['diary'] },
        { id: 'diary-day-items', label: 'Day', icon: DaveActionIcons.calendar, pageLabel: 'All-Day And Milestones', parent: 'dave-layout', order: 4, fn: 'diary.showDay', activeOn: ['diary'] },
        { id: 'diary-search', label: 'Search', icon: DaveActionIcons.filter, pageLabel: 'Diary Search', parent: 'dave-layout', order: 5, fn: 'diary.showSearch', activeOn: ['diary'] },
        { id: 'diary-new-entry', label: 'New Entry', icon: DaveActionIcons.newEntry, pageLabel: 'New Diary Entry', parent: 'dave-layout', order: 6, fn: 'diary.newEntry', activeOn: ['diary'] },
        { id: 'diary-upcoming', label: 'Upcoming', icon: DaveActionIcons.calendar, pageLabel: 'Upcoming Diary Items', parent: 'dave-layout', order: 7, fn: 'diary.showUpcoming', activeOn: ['diary'] },
        { id: 'diary-provenance', label: 'Provenance', icon: DaveActionIcons.document, pageLabel: 'Diary Provenance', parent: 'dave-layout', order: 8, fn: 'diary.showProvenance', activeOn: ['diary'] },
        { id: 'diary-refresh', label: 'Refresh', icon: DaveActionIcons.refresh, pageLabel: 'Refresh Diary', parent: 'dave-layout', order: 9, fn: 'diary.refresh', activeOn: ['diary'] },
        { id: 'diary-view-year', label: 'Mode Year', icon: DaveActionIcons.calendar, pageLabel: 'Calendar Year Mode', parent: 'dave-layout', order: 10, fn: 'diary.goCalendarYear', activeOn: ['diary'] },
        { id: 'diary-view-month', label: 'Mode Month', icon: DaveActionIcons.calendar, pageLabel: 'Calendar Month Mode', parent: 'dave-layout', order: 11, fn: 'diary.goCalendarMonth', activeOn: ['diary'] },
        { id: 'diary-mode-week', label: 'Mode Week', icon: DaveActionIcons.calendar, pageLabel: 'Diary Week Mode', parent: 'dave-layout', order: 12, fn: 'diary.viewWeek', activeOn: ['diary'] },
        { id: 'diary-mode-day', label: 'Mode Day', icon: DaveActionIcons.calendar, pageLabel: 'Diary Day Mode', parent: 'dave-layout', order: 13, fn: 'diary.viewDay', activeOn: ['diary'] },
        { id: 'diary-filter-all', label: 'Filter All', icon: DaveActionIcons.filter, pageLabel: 'Diary All Sources', parent: 'dave-layout', order: 14, fn: 'diary.filterAll', activeOn: ['diary'] },
        { id: 'diary-filter-manual', label: 'Filter Manual', icon: DaveActionIcons.filter, pageLabel: 'Diary Manual Sources', parent: 'dave-layout', order: 15, fn: 'diary.filterManual', activeOn: ['diary'] },
        { id: 'diary-filter-sources', label: 'Filter Sources', icon: DaveActionIcons.filter, pageLabel: 'Diary Source Records', parent: 'dave-layout', order: 16, fn: 'diary.filterSources', activeOn: ['diary'] },
        { id: 'diary-filter-git', label: 'Filter GitHub', icon: DaveActionIcons.filter, pageLabel: 'Diary GitHub Activity', parent: 'dave-layout', order: 17, fn: 'diary.filterGit', activeOn: ['diary'] },
        { id: 'diary-run-summary', label: 'Generate Summary', icon: DaveActionIcons.run, pageLabel: 'Generate Diary Summary', parent: 'dave-layout', order: 18, fn: 'diary.generateSummary', activeOn: ['diary'] },
        { id: 'diary-browse-folder', label: 'Open Day Folder', icon: DaveActionIcons.folder, pageLabel: 'Open Day Folder', parent: 'dave-layout', order: 19, fn: 'diary.openDayFolder', activeOn: ['diary'] },
        { id: 'diary-browse-ledger', label: 'Open Source', icon: DaveActionIcons.document, pageLabel: 'Open Source Ledger', parent: 'dave-layout', order: 20, fn: 'diary.openSourceLedger', activeOn: ['diary'] },
        { id: 'diary-connect-kanban', label: 'Link Kanban', icon: DaveActionIcons.link, pageLabel: 'Link Diary Event To Kanban', parent: 'dave-layout', order: 21, fn: 'diary.linkKanbanItem', activeOn: ['diary'] },
        { id: 'diary-show-pin-private', label: 'Show Pin Private', icon: DaveActionIcons.shield, pageLabel: 'Show Pin-Private Count', parent: 'dave-layout', order: 22, fn: 'diary.showPinPrivate', activeOn: ['diary'] },
        { id: 'diary-explain-event', label: 'Explain', icon: DaveActionIcons.explain, pageLabel: 'Explain Diary State', parent: 'dave-layout', order: 23, fn: 'diary.explainSelection', activeOn: ['diary'] },
        { id: 'diary-safe-checks', label: 'Safe Checks', icon: DaveActionIcons.shield, pageLabel: 'Diary Safe Checks', parent: 'dave-layout', order: 24, fn: 'diary.safeChecks', activeOn: ['diary'] },
        { id: 'calendar-view-cycle', label: 'View', icon: DaveActionIcons.calendar, pageLabel: 'Cycle Calendar View', parent: 'dave-layout', order: 0, fn: 'calendar.toggleContentView', activeOn: ['calender'] },
        { id: 'calendar-filters', label: 'Filters', icon: DaveActionIcons.filter, pageLabel: 'Calendar Filters', parent: 'dave-layout', order: 1, fn: 'calendar.showFilters', activeOn: ['calender'] },
        { id: 'calendar-filter-settings', label: 'Filter Settings', icon: DaveActionIcons.filter, pageLabel: 'Calendar Filter Settings', parent: 'dave-layout', order: 2, fn: 'calendar.showFilterSettings', activeOn: ['calender'] },
        { id: 'calendar-selected', label: 'Selected', icon: DaveActionIcons.document, pageLabel: 'Selected Range Visible Items', parent: 'dave-layout', order: 3, fn: 'calendar.showSelected', activeOn: ['calender'] },
        { id: 'calendar-day-items', label: 'Day', icon: DaveActionIcons.calendar, pageLabel: 'All-Day And Milestones', parent: 'dave-layout', order: 4, fn: 'calendar.showMilestones', activeOn: ['calender'] },
        { id: 'calendar-search', label: 'Search', icon: DaveActionIcons.filter, pageLabel: 'Calendar Search', parent: 'dave-layout', order: 5, fn: 'calendar.showSearch', activeOn: ['calender'] },
        { id: 'calendar-new-event', label: 'New Event', icon: DaveActionIcons.newEntry, pageLabel: 'New Event', parent: 'dave-layout', order: 6, fn: 'calendar.newEvent', activeOn: ['calender'] },
        { id: 'calendar-upcoming', label: 'Upcoming', icon: DaveActionIcons.calendar, pageLabel: 'Upcoming Calendar Items', parent: 'dave-layout', order: 7, fn: 'calendar.showUpcoming', activeOn: ['calender'] },
        { id: 'calendar-provenance', label: 'Provenance', icon: DaveActionIcons.document, pageLabel: 'Calendar Provenance', parent: 'dave-layout', order: 8, fn: 'calendar.showProvenance', activeOn: ['calender'] },
        { id: 'calendar-refresh', label: 'Refresh', icon: DaveActionIcons.refresh, pageLabel: 'Refresh Calendar', parent: 'dave-layout', order: 9, fn: 'calendar.refresh', activeOn: ['calender'] },
        { id: 'calendar-view-year', label: 'Mode Year', icon: DaveActionIcons.calendar, pageLabel: 'Calendar Year Mode', parent: 'dave-layout', order: 10, fn: 'calendar.viewYear', activeOn: ['calender'] },
        { id: 'calendar-view-month', label: 'Mode Month', icon: DaveActionIcons.calendar, pageLabel: 'Calendar Month Mode', parent: 'dave-layout', order: 11, fn: 'calendar.viewMonth', activeOn: ['calender'] },
        { id: 'calendar-mode-day', label: 'Mode Day', icon: DaveActionIcons.calendar, pageLabel: 'Calendar Day Detail', parent: 'dave-layout', order: 12, fn: 'calendar.modeDay', activeOn: ['calender'] },
        { id: 'calendar-mode-week', label: 'Mode Week', icon: DaveActionIcons.calendar, pageLabel: 'Calendar Week Detail', parent: 'dave-layout', order: 13, fn: 'calendar.modeWeek', activeOn: ['calender'] },
        { id: 'calendar-filter-all', label: 'Filter All', icon: DaveActionIcons.filter, pageLabel: 'Calendar All Sources', parent: 'dave-layout', order: 14, fn: 'calendar.filterAll', activeOn: ['calender'] },
        { id: 'calendar-filter-tasks', label: 'Filter Tasks', icon: DaveActionIcons.filter, pageLabel: 'Calendar Tasks', parent: 'dave-layout', order: 15, fn: 'calendar.filterTasks', activeOn: ['calender'] },
        { id: 'calendar-filter-kanban', label: 'Filter Kanban', icon: DaveActionIcons.filter, pageLabel: 'Calendar Kanban', parent: 'dave-layout', order: 16, fn: 'calendar.filterKanban', activeOn: ['calender'] },
        { id: 'calendar-filter-git', label: 'Filter GitHub', icon: DaveActionIcons.filter, pageLabel: 'Calendar GitHub Activity', parent: 'dave-layout', order: 17, fn: 'calendar.filterGit', activeOn: ['calender'] },
        { id: 'calendar-edit-event', label: 'Edit Event', icon: DaveActionIcons.edit, pageLabel: 'Edit Calendar Event', parent: 'dave-layout', order: 18, fn: 'calendar.editSelected', activeOn: ['calender'] },
        { id: 'calendar-open-source', label: 'Open Source', icon: DaveActionIcons.document, pageLabel: 'Calendar Source Detail', parent: 'dave-layout', order: 19, fn: 'calendar.openSource', activeOn: ['calender'] },
        { id: 'calendar-link-diary', label: 'Link Diary', icon: DaveActionIcons.link, pageLabel: 'Open Diary For Date', parent: 'dave-layout', order: 20, fn: 'calendar.linkDiary', activeOn: ['calender'] },
        { id: 'calendar-create-task', label: 'New Task', icon: DaveActionIcons.newEntry, pageLabel: 'New Calendar Task', parent: 'dave-layout', order: 21, fn: 'calendar.createTask', activeOn: ['calender'] },
        { id: 'calendar-connect-kanban', label: 'Link Kanban', icon: DaveActionIcons.link, pageLabel: 'Link Calendar Event To Kanban', parent: 'dave-layout', order: 22, fn: 'calendar.linkKanbanItem', activeOn: ['calender'] },
        { id: 'calendar-explain', label: 'Explain', icon: DaveActionIcons.explain, pageLabel: 'Explain Calendar State', parent: 'dave-layout', order: 23, fn: 'calendar.explainSelection', activeOn: ['calender'] },
        { id: 'calendar-safe-checks', label: 'Safe Checks', icon: DaveActionIcons.shield, pageLabel: 'Calendar Safe Checks', parent: 'dave-layout', order: 24, fn: 'calendar.safeChecks', activeOn: ['calender'] },
        { id: 'todo-new-task', label: 'New Task', icon: DaveActionIcons.newEntry, pageLabel: 'New ToDo Task', parent: 'dave-layout', order: 0, fn: 'todo.newTask', activeOn: ['todo'] },
        { id: 'todo-refresh', label: 'Refresh', icon: DaveActionIcons.refresh, pageLabel: 'Refresh ToDo', parent: 'dave-layout', order: 1, fn: 'todo.refresh', activeOn: ['todo'] },
        { id: 'todo-mode-today', label: 'Mode Today', icon: DaveActionIcons.filter, pageLabel: 'ToDo Today Mode', parent: 'dave-layout', order: 2, fn: 'todo.modeToday', activeOn: ['todo'] },
        { id: 'todo-mode-personal', label: 'Mode Personal', icon: DaveActionIcons.filter, pageLabel: 'ToDo Personal Mode', parent: 'dave-layout', order: 3, fn: 'todo.modePersonal', activeOn: ['todo'] },
        { id: 'todo-mode-kanban', label: 'Mode Kanban', icon: DaveActionIcons.filter, pageLabel: 'ToDo Kanban Mode', parent: 'dave-layout', order: 4, fn: 'todo.modeKanban', activeOn: ['todo'] },
        { id: 'todo-mode-blocked', label: 'Mode Blocked', icon: DaveActionIcons.shield, pageLabel: 'ToDo Blocked Mode', parent: 'dave-layout', order: 5, fn: 'todo.modeBlocked', activeOn: ['todo'] },
        { id: 'todo-mode-review', label: 'Mode Review', icon: DaveActionIcons.explain, pageLabel: 'ToDo Review Mode', parent: 'dave-layout', order: 6, fn: 'todo.modeReview', activeOn: ['todo'] },
        { id: 'todo-mode-done', label: 'Mode Done', icon: DaveActionIcons.complete, pageLabel: 'ToDo Done Mode', parent: 'dave-layout', order: 7, fn: 'todo.modeDone', activeOn: ['todo'] },
        { id: 'todo-edit-task', label: 'Edit Task', icon: DaveActionIcons.edit, pageLabel: 'Edit ToDo Task', parent: 'dave-layout', order: 8, fn: 'todo.editSelected', activeOn: ['todo'] },
        { id: 'todo-complete-task', label: 'Complete Task', icon: DaveActionIcons.complete, pageLabel: 'Complete ToDo Task', parent: 'dave-layout', order: 9, fn: 'todo.completeSelected', activeOn: ['todo'] },
        { id: 'todo-archive-task', label: 'Archive Task', icon: DaveActionIcons.archive, pageLabel: 'Archive ToDo Task', parent: 'dave-layout', order: 10, fn: 'todo.archiveSelected', activeOn: ['todo'] },
        { id: 'todo-open-source', label: 'Open Source', icon: DaveActionIcons.document, pageLabel: 'ToDo Source Detail', parent: 'dave-layout', order: 11, fn: 'todo.openSource', activeOn: ['todo'] },
        { id: 'todo-connect-kanban', label: 'Link Kanban', icon: DaveActionIcons.link, pageLabel: 'Link ToDo Task To Kanban', parent: 'dave-layout', order: 12, fn: 'todo.linkKanbanItem', activeOn: ['todo'] },
        { id: 'todo-promote-kanban', label: 'Promote To Kanban', icon: DaveActionIcons.link, pageLabel: 'Promote ToDo Task To Kanban', parent: 'dave-layout', order: 13, fn: 'todo.promoteToKanban', activeOn: ['todo'] },
        { id: 'todo-explain', label: 'Explain', icon: DaveActionIcons.explain, pageLabel: 'Explain ToDo State', parent: 'dave-layout', order: 14, fn: 'todo.explainSelection', activeOn: ['todo'] },
        { id: 'todo-safe-checks', label: 'Safe Checks', icon: DaveActionIcons.shield, pageLabel: 'ToDo Safe Checks', parent: 'dave-layout', order: 15, fn: 'todo.safeChecks', activeOn: ['todo'] },
        { id: 'email-refresh', label: 'Refresh', icon: DaveActionIcons.refresh, pageLabel: 'Refresh Email', parent: 'dave-layout', order: 0, fn: 'email.refresh', activeOn: ['email'] },
        { id: 'email-browse-folders', label: 'Browse Folders', icon: DaveActionIcons.folder, pageLabel: 'Browse Email Folders', parent: 'dave-layout', order: 1, fn: 'email.browseFolders', activeOn: ['email'] },
        { id: 'email-view-plain', label: 'Mode Plain', icon: DaveActionIcons.document, pageLabel: 'Plain Email View', parent: 'dave-layout', order: 2, fn: 'email.viewPlain', activeOn: ['email'] },
        { id: 'email-view-html', label: 'Mode HTML', icon: DaveActionIcons.document, pageLabel: 'Sanitized HTML Email View', parent: 'dave-layout', order: 3, fn: 'email.viewHtml', activeOn: ['email'] },
        { id: 'email-view-markdown', label: 'Mode Markdown', icon: DaveActionIcons.document, pageLabel: 'Markdown Email View', parent: 'dave-layout', order: 4, fn: 'email.viewMarkdown', activeOn: ['email'] },
        { id: 'email-toggle-list', label: 'Toggle List', icon: DaveActionIcons.document, pageLabel: 'Collapse Or Expand Email List', parent: 'dave-layout', order: 5, fn: 'email.toggleList', activeOn: ['email'] },
        { id: 'email-safe-checks', label: 'Safe Checks', icon: DaveActionIcons.shield, pageLabel: 'Email Safe Checks', parent: 'dave-layout', order: 6, fn: 'email.safeChecks', activeOn: ['email'] },
        { id: 'imports-refresh', label: 'Refresh', icon: 'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 24 24%22%3E%3Cpath fill=%22black%22 d=%22M13 3a9 9 0 1 0 8.95 10h-2.02A7 7 0 1 1 12 5a6.97 6.97 0 0 1 4.24 1.43L13 10h8V2l-3.33 3.33A8.97 8.97 0 0 0 13 3z%22/%3E%3C/svg%3E', pageLabel: 'Refresh Imports', parent: 'dave-layout', order: 0, fn: 'imports.refresh', activeOn: ['imports'] },
        { id: 'imports-source-doc', label: 'Open Source', icon: 'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 24 24%22%3E%3Cpath fill=%22black%22 d=%22M6 2h8l5 5v15H6V2zm7 1.5V8h4.5L13 3.5zM8 12h8v2H8v-2zm0 4h8v2H8v-2z%22/%3E%3C/svg%3E', pageLabel: 'Open Imports Source', parent: 'dave-layout', order: 1, fn: 'imports.openInterestsDoc', activeOn: ['imports'] },
        { id: 'imports-latest-proof', label: 'Open Proof', icon: 'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 24 24%22%3E%3Cpath fill=%22black%22 d=%22M5 3h14v18H5V3zm3 4h8v2H8V7zm0 4h8v2H8v-2zm0 4h5v2H8v-2z%22/%3E%3C/svg%3E', pageLabel: 'Open Latest Proof', parent: 'dave-layout', order: 2, fn: 'imports.openLatestProof', activeOn: ['imports'] },
        { id: 'imports-artifacts', label: 'Open Artifacts', icon: 'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 24 24%22%3E%3Cpath fill=%22black%22 d=%22M4 5h6l2 2h8v12H4V5zm2 4v8h12V9H6z%22/%3E%3C/svg%3E', pageLabel: 'Open Artifacts', parent: 'dave-layout', order: 3, fn: 'imports.openArtifacts', activeOn: ['imports'] },
        { id: 'imports-blockers', label: 'Show Blockers', icon: 'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 24 24%22%3E%3Cpath fill=%22black%22 d=%22M1 21h22L12 2 1 21zm12-3h-2v-2h2v2zm0-4h-2v-4h2v4z%22/%3E%3C/svg%3E', pageLabel: 'Show Blockers', parent: 'dave-layout', order: 4, fn: 'imports.showBlockers', activeOn: ['imports'] },
        { id: 'imports-explain', label: 'Explain', icon: 'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 24 24%22%3E%3Cpath fill=%22black%22 d=%22M11 18h2v-2h-2v2zm1-16a10 10 0 1 0 0 20 10 10 0 0 0 0-20zm0 18a8 8 0 1 1 0-16 8 8 0 0 1 0 16zm0-14a3 3 0 0 0-3 3h2a1 1 0 1 1 1 1c-1.1 0-2 .9-2 2v2h2v-2a3 3 0 0 0 0-6z%22/%3E%3C/svg%3E', pageLabel: 'Explain Status', parent: 'dave-layout', order: 5, fn: 'imports.explainStatus', activeOn: ['imports'] },
        { id: 'imports-safe-checks', label: 'Safe Checks', icon: 'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 24 24%22%3E%3Cpath fill=%22black%22 d=%22M12 2 4 5v6c0 5 3.4 9.7 8 11 4.6-1.3 8-6 8-11V5l-8-3zm-1 14-4-4 1.4-1.4 2.6 2.6 5.6-5.6L18 9l-7 7z%22/%3E%3C/svg%3E', pageLabel: 'Safe Status Checks', parent: 'dave-layout', order: 6, fn: 'imports.safeChecks', activeOn: ['imports'] },
        { id: 'imports-filter-all', label: 'Filter All', icon: 'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 24 24%22%3E%3Cpath fill=%22black%22 d=%22M3 5h18v2H3V5zm4 6h10v2H7v-2zm3 6h4v2h-4v-2z%22/%3E%3C/svg%3E', pageLabel: 'Filter All Sources', parent: 'dave-layout', order: 7, fn: 'imports.filterAll', activeOn: ['imports'] },
        { id: 'imports-filter-interests', label: 'Filter Interests', icon: 'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 24 24%22%3E%3Cpath fill=%22black%22 d=%22M12 3 2 12h3v8h14v-8h3L12 3zm0 3.7 4 3.6V18H8v-7.7l4-3.6z%22/%3E%3C/svg%3E', pageLabel: 'Filter Interests', parent: 'dave-layout', order: 8, fn: 'imports.filterInterests', activeOn: ['imports'] },
        { id: 'imports-filter-git', label: 'Filter Git', icon: 'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 24 24%22%3E%3Cpath fill=%22black%22 d=%22M7 3a3 3 0 0 1 2.8 2H14a3 3 0 1 1 0 2H9.8A3 3 0 0 1 8 8.8v6.4A3 3 0 1 1 6 15.2V8.8A3 3 0 0 1 7 3zm10 2a1 1 0 1 0 0 2 1 1 0 0 0 0-2zM7 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm0 12a1 1 0 1 0 0 2 1 1 0 0 0 0-2z%22/%3E%3C/svg%3E', pageLabel: 'Filter Git', parent: 'dave-layout', order: 9, fn: 'imports.filterGit', activeOn: ['imports'] },
    ],
});
