import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const index = readFileSync(resolve(root, 'index.html'), 'utf8');
const js = readFileSync(resolve(root, 'js/settings/matrix-chat.js'), 'utf8');
const activeBrowserJs = readFileSync(resolve(root, 'js/active-browser-observer.js'), 'utf8');
const css = readFileSync(resolve(root, 'css/matrix-chat.css'), 'utf8');

assert.match(index, /id="matrix-chat-attachment-modal"/);
assert.match(index, /id="matrix-chat-attachment-download"/);
assert.match(index, /id="matrix-chat-attachment-preview"/);

assert.match(js, /function openAttachmentModal/);
assert.match(js, /function attachmentBlobEntry/);
assert.match(js, /apiFetch\(attachmentDownloadPath/);
assert.match(js, /signal:\s*options\.signal/);
assert.match(js, /apiJson\(attachmentPreviewPath/);
assert.match(js, /URL\.createObjectURL\(blob\)/);
assert.match(js, /URL\.revokeObjectURL/);
assert.match(js, /function scheduleInlineImageHydration/);
assert.match(js, /new IntersectionObserver/);
assert.match(js, /observer\.observe\(button\)/);
assert.match(js, /state\.inlineImageAbortController\?\.signal/);
assert.match(js, /function cancelMessageLoad/);
assert.match(js, /new AbortController\(\)/);
assert.match(js, /isCurrentMessageLoad\(token, roomId\)/);
assert.match(js, /error\?\.name === 'AbortError'[\s\S]*return false/);
assert.match(js, /MATRIX_CHAT_INITIAL_MESSAGE_LIMIT = 60/);
assert.match(js, /MATRIX_CHAT_INITIAL_DECRYPT_TIMEOUT_MS = 0/);
assert.match(js, /MATRIX_CHAT_OLDER_DECRYPT_TIMEOUT_MS = 0/);
assert.match(js, /MATRIX_CHAT_PROGRESSIVE_BACKFILL_TARGET = 30/);
assert.match(js, /MATRIX_CHAT_PROGRESSIVE_BACKFILL_DECRYPT_TIMEOUT_MS = 4500/);
assert.match(js, /decrypt_timeout_ms=\$\{MATRIX_CHAT_INITIAL_DECRYPT_TIMEOUT_MS\}/);
assert.match(js, /decrypt_timeout_ms=\$\{MATRIX_CHAT_OLDER_DECRYPT_TIMEOUT_MS\}/);
assert.match(js, /function loadProgressiveBackfill/);
assert.match(js, /lastHistoryBackfillMetrics/);
assert.match(js, /server_metrics = data\.metrics \|\| null/);
assert.match(js, /lastRefreshMetrics/);
assert.match(js, /lastMessageLoadMetrics/);
assert.match(js, /last_history_backfill/);
assert.match(js, /function snapshot\(\)/);
assert.match(js, /status_ms/);
assert.match(js, /rooms_ms/);
assert.match(js, /messages_ms/);
assert.match(js, /inline_images: inlineImageSnapshot\(\)/);
assert.match(activeBrowserJs, /matrixChatSnapshot/);
assert.match(activeBrowserJs, /surfaces\.matrix_chat = matrixChatSnapshot/);
assert.doesNotMatch(js, /onclick=/);

assert.match(css, /\.matrix-chat-inline-image-button/);
assert.match(css, /\.matrix-chat-attachment-preview-image/);
assert.match(css, /\.matrix-chat-attachment-audio-icon/);
assert.match(css, /speaker-blue\.svg/);
