let _services = [];
let _machines = [];
let _nodes    = [];
let _settings = [];
let _nodeName   = '';
let _selfNodeId  = '';  // node_id from /health (may differ from display name)
let _activeGroup = 'synthesis';
let _pfsenseDns = [];
let _proxmoxConfig = [];
let _proxmoxNetsMap = {};  // config_id -> [net, ...]
let _dockgeStacks = [];
let _dockgeServicesMap = {};  // stack_id -> [service, ...]
let _caddyConfigs = [];
let _pveHosts = [];
let _vlans = [];
let _arpManual = [];
let _sshTargets = [];
let _manualLinks = [];
let _aiProviders = [];
let _aiAssignments = [];
let _bookmarks = [];
let _bmVisits  = [];
let _keys = [];
let _parsedBundle = [];   // parsed key entries from import textarea
let _pctPollInterval = null;
